name: custom_rating_bar
description: >- 
  Custom rating bar for flutter with support of 
  custom icons, half icons, directions, alignments & more.
version: 3.0.0
homepage: https://github.com/eterkit/flutter-packages/tree/main/custom_rating_bar
repository: https://github.com/eterkit/flutter-packages
screenshots:
  - description: 'Examples usage of rating bars.'
    path: examples.png

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  import_sorter: ^4.6.0

flutter:

import_sorter:
  comments: false