name: permission_guard
description: >-
  UI wrapper around permission_handler package 
  that makes handling permission states easy.
version: 1.0.2
homepage: https://github.com/eterkit/flutter-packages/tree/main/permission_guard
screenshots:
  - description: 'Example of permission guard in a widget.'
    path: widget.gif
  - description: 'Example of permission guard in a dialog.'
    path: dialog.gif

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0

flutter:

import_sorter:
  comments: false
